In [1]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X) # max of array
y = y/100
def sigmoid (x):
 return 1/(1 + np.exp(-x))
def derivatives_sigmoid(x):
 return x * (1 - x)
epoch=5000
lr=0.1
wh = np.random.uniform(size=(2,3))
bh = np.random.uniform(size=(1,3))
wout = np.random.uniform(size=(3,1))
bout = np.random.uniform(size=(1,1))
for i in range(epoch):
 # forward prop
 hinp=np.dot(X,wh) + bh
 hlayer_act = sigmoid(hinp)
 outinp=np.dot(hlayer_act,wout) + bout
 output = sigmoid(outinp)
 hiddengrad = derivatives_sigmoid(hlayer_act)
 outgrad = derivatives_sigmoid(output)

 EO = y-output
 d_output = EO* outgrad

 EH = d_output.dot(wout.T)
 d_hiddenlayer = EH * hiddengrad
 wout += hlayer_act.T.dot(d_output) *lr
 wh += X.T.dot(d_hiddenlayer) *lr
 print("Input: \n" + str(X))
 print("Actual Output: \n" + str(y))
 print("Predicted Output: \n" ,output)


Streaming output truncated to the last 5000 lines.
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89408075]
 [0.88482285]
 [0.89105947]]
Input: 
[[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89408083]
 [0.88482278]
 [0.89105945]]
Input: 
[[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.8940809 ]
 [0.88482271]
 [0.89105942]]
Input: 
[[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89408098]
 [0.88482264]
 [0.8910594 ]]
Input: 
[[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89408105]
 [0.88482258]
 [0.89105938]]
Input: 
[[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]]
Actual Ou